# Generated by Django 4.1.6 on 2023-02-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bio', models.CharField(default=' ', max_length=200)),
                ('user_picture', models.FileField(blank=True, upload_to='')),
                ('followers', models.ManyToManyField(blank=True, related_name='user_following', to=settings.AUTH_USER_MODEL)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
