# Generated by Django 4.1.6 on 2023-02-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_rename_input_text_post_post_input_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_type',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
