# Generated by Django 4.1.6 on 2023-02-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_profile_picture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
