# Generated by Django 4.1.6 on 2023-03-07 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_alter_profile_picture_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='input_text',
            new_name='comment_input_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='comment_post', to='socialnetwork.post'),
            preserve_default=False,
        ),
    ]
